Implementation
kitade-shogo/mokumoku pull request #2
Opened 2023-03-01 11:52 UTC by kitade-shogo

「事業をエンジニアリングしよう ②実装」について、課題要件を満たすよう機能を実装しました。
レビューの程、よろしくお願い致します。

**選択した事業課題**
直近一年間で、2回以上もくもく会に参加してくれた人は利用者全体の1%のみ。もくもく会で気の合う仲間を見つけられなかったのではないか？

**テスト結果**
<img width="467" alt="スクリーンショット 2023-03-01 20 49 59" src="https://user-images.githubusercontent.com/108001521/222131318-96587957-ffff-4454-8e6f-1f9948a49387.png">

2023-03-02 09:55 UTC, busitora requested changes

2023-03-02 09:55 UTC, busitora commented on app/controllers/organizer_controller.rb
> +        @organizer = User.find(params[:id])
```suggestion
       @organizer = User.find(params[:id])
```

2023-03-02 09:55 UTC, busitora commented on app/decorators/attendee_decorator.rb
> +class AttendeeDecorator < Draper::Decorator
不要なのであれば消しましょう！（以下同文です）

2023-03-02 09:55 UTC, busitora commented on app/models/event.rb
> +  def self.ransackable_attributes(auth_object = nil)
こちらの実装の意図はなんでしょうか？

2023-03-02 09:55 UTC, busitora commented on app/models/relationship.rb
> +    belongs_to :follower, class_name: "User"
```suggestion
  belongs_to :follower, class_name: "User"
```

無駄なスペース消してください〜

2023-03-02 09:55 UTC, busitora commented on app/models/user.rb
> +
無駄な空白

2023-03-02 09:55 UTC, busitora commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
find_by でnilだった時の考慮、考えてみてください！

2023-03-02 09:55 UTC, busitora commented on app/views/attendees/show.html.erb
> +<% if current_user != @attendee %>
if がネストしているので、一つのメソッドにまとめてみてください

2023-03-02 12:34 UTC, kitade-shogo commented on app/controllers/organizer_controller.rb
> +        @organizer = User.find(params[:id])
修正しました！

2023-03-02 12:35 UTC, kitade-shogo commented on app/decorators/attendee_decorator.rb
> +class AttendeeDecorator < Draper::Decorator
自分で追加したDecoratorファイルは全て削除しました！

2023-03-02 12:35 UTC, kitade-shogo commented on app/models/relationship.rb
> +    belongs_to :follower, class_name: "User"
削除しました！

2023-03-02 12:35 UTC, kitade-shogo commented on app/models/user.rb
> +
削除しました！

2023-03-02 12:36 UTC, kitade-shogo commented on app/models/user.rb
> +    relationships.find_by(followed_id: user_id).destroy
修正しました。

2023-03-02 12:39 UTC, kitade-shogo commented on app/views/attendees/show.html.erb
> +<% if current_user != @attendee %>
修正しました。
application_helper に current_user? メソッドを定義し、unlessで分岐しました。

2023-03-02 12:44 UTC, kitade-shogo commented on app/models/event.rb
> +  def self.ransackable_attributes(auth_object = nil)
ransackのversion 4.0.0 のアップデートで関係するモデルにホワイトリストを登録する必要が出てきたそうで、こちらはそのホワイトリストを登録するメソッドとなります。
(参考: https://qiita.com/Yamashita-Taiki/items/764be62a8c20485ece54)

2023-03-02 12:47 UTC, kitade-shogo commented
レビュー及びご指摘ありがとうございます！
ご指摘を頂いた点全て修正致しました。
再レビューのほど、よろしくお願い致します。

2023-03-02 12:59 UTC, busitora requested changes

2023-03-02 12:59 UTC, busitora commented on app/models/user.rb
> +  def follow!(user_id)
メソッドに ! はあまり使わないのですが、意図はなんでしょうか？

2023-03-02 12:59 UTC, busitora commented on app/models/user.rb
> +  def unfollow!(user_id)
find_by で nil の場合 はretrunするようにするといいと思います！

変数を格納してそのまま if 文として評価するより

```ruby
relationship = relationships.find_by(followed_id: user_id)
return if relationship.nil?

relationship.destroy
```

ですね。

2023-03-02 13:14 UTC, kitade-shogo commented on app/models/user.rb
> +  def follow!(user_id)
定義したメソッド内でdestroy!等のメソッドを使用しているのをわかりやすくする為に付けていました。
修正しました。

2023-03-02 13:20 UTC, kitade-shogo commented on app/models/user.rb
> +  def unfollow!(user_id)
ありがとうございます！
これまでモデルやコントローラ内でreturnを使った経験が少ないので無意識に避けていました、勉強します。

2023-03-02 13:21 UTC, kitade-shogo commented
再レビューでご指摘頂いた2点に関して修正しました。

2023-03-03 11:51 UTC, takyyk commented
@kitade-shogo 
LGTMです！！

2023-03-03 11:54 UTC, kitade-shogo commented
レビューありがとうございました！
こちらのPRは閉じさせて頂きます。

2023-03-03 11:54 UTC, closed without merging